### ISSUE TITLE
Support AWS provider 3.x

### ISSUE THREAD

**Issue by sgrimm** [cloudposse/terraform-aws-lb-s3-bucket#23]
## Describe the Feature
Version 2.x of the AWS provider is no longer being actively developed but is required by this module.

## Expected Behavior
The module should work with the current version of the AWS provider.

## Use Case
I ran into this when trying to use https://github.com/cloudposse/terraform-aws-alb with version 3.x of the provider (which that module claims to support) because it depends on this module.

## Additional Context
From quick inspection, it doesn't look like this module is doing anything that would break with the current provider version.

**Comment by tirumerla** [comment]
I have the same issue. Fix is to pin s3 bucket module to `0.14.0` tag  instead of `0.13.1`
```
module "s3_bucket" {
  source  = "git::https://github.com/cloudposse/terraform-aws-s3-log-storage.git?ref=tags/0.13.1"
```
