### ISSUE TITLE
Allow for passing additional bucket policy

### ISSUE THREAD

**Issue by razorsedge** [cloudposse/terraform-aws-lb-s3-bucket#50]
## Describe the Feature

This module is opinionated and does not allow to modify the s3 bucket policy in any way.

## Expected Behavior

Allow for the input of additional bucket policy.

## Use Case

We have need to allow a separate AWS account to access the ELB logs in s3.  i.e. Running Athena queries from one account against s3 buckets in other accounts.  This module does not allow to modify the s3 bucket policy in any way.

## Describe Ideal Solution

Allow for an input named `additional_policy` that will merge with the policy created in this module and then be passed on to the s3 bucket creation.

**Comment by Nuru** [comment]
This module is highly opinionated. One hint is the "lb" in the name, which means this has been specialized for load balancer logs. 

Although your request is in line with using a load balancer, in general, Cloud Posse is no longer enhancing these highly specialized modules. If this module is not sufficient for your purposes, use the more general modules [terraform-aws-s3-log-storage](terraform-aws-s3-log-storage) or [https://github.com/cloudposse/terraform-aws-s3-bucket](https://github.com/cloudposse/terraform-aws-s3-bucket).
