### ISSUE TITLE
Deprecation warnings - bump `cloudposse/s3-log-storage/aws` to 0.28.2

### ISSUE THREAD

**Issue by mwos-sl** [cloudposse/terraform-aws-lb-s3-bucket#55]
I'm getting deprecation warnings:
```
│ Warning: Argument is deprecated
│
│   with module.alb-logs.module.s3_bucket.module.aws_s3_bucket.aws_s3_bucket.default,
│   on .terraform/modules/alb-logs.s3_bucket.aws_s3_bucket/main.tf line 30, in resource "aws_s3_bucket" "default":
│   30: resource "aws_s3_bucket" "default" {
│
│ Use the top-level parameter object_lock_enabled and the aws_s3_bucket_object_lock_configuration resource instead
```

~Related to downstream: https://github.com/cloudposse/terraform-aws-s3-log-storage/issues/74
The above has to be done first, then this: https://github.com/cloudposse/terraform-aws-lb-s3-bucket/blob/master/main.tf#L63
has to be bumped after `aws-s3-log-storage` is released.~

New `cloudposse/s3-log-storage/aws` is already released under `0.28.2`

## Versions
terraform 1.0.7
aws provider 4.27.0
`cloudposse/lb-s3-bucket/aws` 0.16.0

**Comment by wosiu** [comment]
There is a new release `cloudposse/s3-log-storage/aws`, version should be bumped here from `0.28.0` to `0.28.2`
